# Generated by Django 6.0.5 on 2026-05-22 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0002_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain spaces and letters.', regex='^[A-Za-z0-9 @.+\\-_]+$')]),
        ),
    ]
