# Generated by Django 6.0.5 on 2026-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0003_alter_customuser_phone_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
