# Generated by Django 6.0.5 on 2026-07-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0008_alter_cart_unique_together_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_mould_women_sling',
            field=models.BooleanField(default=False),
        ),
    ]
