# Generated by Django 6.0.5 on 2026-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0010_placeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='is_order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
