# Generated by Django 6.0.5 on 2026-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0011_placeorder_is_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='save_address',
            field=models.BooleanField(default=False),
        ),
    ]
