# Generated by Django 6.0.5 on 2026-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0012_placeorder_save_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_convoy_briefcase',
            field=models.BooleanField(default=False),
        ),
    ]
