# Generated by Django 6.0.5 on 2026-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0013_product_show_in_convoy_briefcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_transit_crossbag',
            field=models.BooleanField(default=False),
        ),
    ]
