# Generated by Django 6.0.5 on 2026-07-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0014_product_show_in_transit_crossbag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
