# Generated by Django 6.0.5 on 2026-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0016_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
