# Generated by Django 6.0.5 on 2026-09-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0017_customuser_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deletion_requested_at',
        ),
    ]
