# Generated by Django 6.0.5 on 2026-09-02 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0018_remove_customuser_deletion_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain spaces and letters.', regex='^[A-Za-z0-9 @.+**\\\\-**\\_]+$')]),
        ),
    ]
