# Generated by Django 6.0.5 on 2026-09-04 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0019_customuser_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers, spaces, @, ., +, *, - and _.', regex='^[A-Za-z0-9 @.+*_-]+$')]),
        ),
    ]
