# Generated by Django 6.0.5 on 2026-09-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideapp', '0020_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
